// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Keke_SpeedStarBattle","status":true,"description":"流れるように疾走する快速バトル","parameters":{"バトルウェイト":"","基本バトルウェイト":"40","バトルウェイト補正(短)":"0.25","バトルウェイト補正(長)":"0.25","バトルウェイト乱数":"0","各動作速度":"","アニメ速度":"1.1","ムーブ速度":"1.1","モーション速度":"1.1","エフェクト速度":"1.1","連続アニメディレイ":"4","早送り倍率":"5","タイムプログレス速度":"","タイムゲージ速度":"1","タイムオートファスト":"5","ウェイト":"","基本ポップウェイト":"25","通常コラプスウェイト":"0","ボスコラプスウェイト":"-1","その他":"","オプションに追加":"true","オプション設定":"{\"バトルスピード最大値\":\"500\",\"バトルスピード最低値\":\"10\",\"バトルスピード増減値\":\"10\"}","オプション追加リスト":"[\"a-バトルスピード\"]","バトルログ無効":"false"}},
{"name":"PlayerMoveSpeedOptions","status":true,"description":"Adds walking and running speed settings to the options menu.","parameters":{"MinSpeed":"3","MaxSpeed":"6","DefaultWalkSpeed":"4","DefaultDashSpeed":"5"}},
{"name":"LicenseNotice","status":true,"description":"Adds a credits and licenses item to the title menu.","parameters":{}},
{"name":"VerticalDisplayFullscreen","status":true,"description":"Expands map and battle visuals for portrait screens while keeping the PC-style UI centered.","parameters":{"PortraitOnly":"true","MaxScreenHeight":"1800","DesktopPortraitPreview":"true","MapScale":"2.00"}},
{"name":"MobileTouchControls","status":true,"description":"Adds on-screen controls for touch devices.","parameters":{}},
{"name":"MainFontLetterSpacing","status":true,"description":"Adjusts the letter spacing of the main game font.","parameters":{"HiraganaSpacing":"-9.00","KatakanaSpacing":"-10.00","KanjiSpacing":"-8.00","LatinNumberSpacing":"-2.00","LetterSpacing":"-2.00"}},
{"name":"HideTouchBackMenuButtons","status":true,"description":"タッチ操作用の戻るボタンとメニューボタンを非表示にします。","parameters":{}},
{"name":"FlexibleTopDownUI","status":true,"description":"Responsive UI layout: Horizontal top-aligned commands & bottom-aligned help window for PC and Mobile.","parameters":{"MobileBreakpointWidth":"640"}},
{"name":"DisableMouseMapClickMove","status":true,"description":"Prevents mouse-originated clicks from moving the player on the map.","parameters":{}},
{"name":"HUG/LN_FilmicFilter","status":true,"description":"LN_FilmicFilter v1.1.1 (MIT License)","parameters":{"EditorKey":"F11"}}
];
