// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MobileTouchControls","status":true,"description":"Adds on-screen controls for touch devices.","parameters":{}}
];
