// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"VerticalDisplayFullscreen","status":true,"description":"Expands map and battle visuals for portrait screens while keeping the PC-style UI centered.","parameters":{"PortraitOnly":"true","MaxScreenHeight":"1800"}},
{"name":"MobileTouchControls","status":true,"description":"Adds on-screen controls for touch devices.","parameters":{}},
{"name":"LicenseNotice","status":true,"description":"Adds a credits and licenses item to the title menu.","parameters":{}}
];
